### ISSUE TITLE
Скрипт не будет работать

### ISSUE THREAD

**Issue by eremeyko** [Horockey/Get-vk-info-script#1]
Проблема в абсолютной указанной директории:
```Python
...
img_filename = "C:\\\\Users\\Horockey\\Desktop\\Photo_"
info_filename = "C:\\\\Users\\Horockey\\Desktop\\Info_"
...
```  

У других пользователей просто нет такого пути

Может в ReadMe описать для чего должны быть предназначены эти папки, чтобы каждый указал свою

**Comment by Horockey** [comment]
Спасибо за отзыв! Совсем забыл убрать перед публикацией этот момент)
Обновил код, убрал абсолютную адресацию, добавил возможность указывать пользовательский путь сохранения.
